### ISSUE TITLE
wierd border on the left

### ISSUE THREAD

**Issue by glyh** [nyoom-engineering/nyoom.nvim#100]
![image](https://user-images.githubusercontent.com/12870742/209230480-5da12550-e888-4b37-a512-60f7a6d15c9a.png)
To repreat: 
1. start nyoom
2. press `:ls`

**Comment by shaunsingh** [comment]
Those are actually fold icons, that you can use to identify whats foldable and whats not (`zM` and `zR`). They should probably be disabled on the startup screen though, I'll get to that
