### ISSUE TITLE
Apparent typo in `nvim-dev-container` url

### ISSUE THREAD

**Issue by ohmree** [nyoom-engineering/nyoom.nvim#102]
Hi, as a diehard doom (and emacs) lover this project looks really promising given neovim's current superior support (IMO) for stuff like DAP and multi-language files with tree-sitter (web-mode is a horrible horrible hack that should and will hopefully die when emacs 29 comes out with built-in tree-sitter support but I digress).
When running `nyoom sync` for the first time it asked me for credentials for codeberg, which I _think_ might be because of this typo:
https://github.com/nyoom-engineering/nyoom.nvim/blob/b3423c22445f86188db5ccd966d94eb722a8df0b/fnl/modules/tools/docker/init.fnl#L3

`s/containe/container`, no?

**Comment by shaunsingh** [comment]
Yup, thanks and fixed
