### ISSUE TITLE
Requesting to make a Matrix group.

### ISSUE THREAD

**Issue by Absinthe8383** [nyoom-engineering/nyoom.nvim#106]
As you know fennel have a group on matrix and I think people using this project are also interested in fennel, so making a matrix group will both help people ask doubt and get familiar with fennel as both of the things will be present there and some people might not use discord.

**Comment by shaunsingh** [comment]
While I personally do not use matrix much, I can understand why others would want a matrix chat. However, most of my chatting is done through discord and I'd probably end up neglecting the matrix group more often than not. 

Would it be a good compromise to have a bridge between matrix/irc and discord? So users can interact on either platform

**Comment by Absinthe8383** [comment]
> While I personally do not use matrix much, I can understand why others would want a matrix chat. However, most of my chatting is done through discord and I'd probably end up neglecting the matrix group more often than not.
> 
> Would it be a good compromise to have a bridge between matrix/irc and discord? So users can interact on either platform

Yeah, that would be good if you don't use matrix that actively ;)

**Comment by thefossenjoyer** [comment]
A matrix bridge? Sounds good to me.

**Comment by Jaggernaute** [comment]
I've seen it done via `matterbot` (a bot that uses [matterbridge](https://github.com/42wim/matterbridge)) on the QTile's discord server 
![image](https://user-images.githubusercontent.com/42418858/211212322-745f251d-2de9-4680-b5cb-fea171c3756a.png)

**Comment by luxus** [comment]
what have mattermost todo with bridging discord and matrix?

i bridged some channels with https://github.com/mautrix/discord in the past.. 
dunno if its worth the effort :D

**Comment by Jaggernaute** [comment]
just putting how I've seen other people do it, your solution seems to be much simpler to put in place, but it doesn't seems to leave a lot of room for future integration like slack or telegram (if it's requested), but yeah is it worth it ? IDK

**Comment by thefossenjoyer** [comment]
Looks like not.

**Comment by Absinthe8383** [comment]
@shaunsingh any answer for this?

**Comment by Absinthe8383** [comment]
its been around 2 years, So I think I should close this issue
