### ISSUE TITLE
Error when editing rust code with bevy

### ISSUE THREAD

**Issue by misterzirillo** [nyoom-engineering/nyoom.nvim#107]
I've been trying out nyoom and getting this error while working on a project

![image](https://user-images.githubusercontent.com/4575207/211941768-4154e15f-6984-4f43-9613-8100f6b576b3.png)

I can reliably get this error message by creating a new rust project with `cargo new` and adding bevy as a dependency then beginning editing.

**Comment by shaunsingh** [comment]
https://github.com/simrat39/rust-tools.nvim/issues/300

Looks to be the same as this issue, it seems I need to bump the version of `rust-tools`. I'll update it shortly

**Comment by misterzirillo** [comment]
Thanks for the quick response! Is there any way I can update my configuration temporarily?

**Comment by shaunsingh** [comment]
Sorry for the delay, should be fixed now!
