### ISSUE TITLE
After it opens, i simply can't do anything, it stays stuck in 'Downloading tree-sitter-comment' until i force close my terminal

### ISSUE THREAD

**Issue by hrqmonteiro** [nyoom-engineering/nyoom.nvim#108]
[Screencast from 2023-01-13 21-25-53.webm](https://user-images.githubusercontent.com/17055027/212441075-8beab8b3-ca4c-491f-9a16-1bad9b23c361.webm)

If i try to open a file, try to type on the cmdline or do anything actually, it just stays stuck and i have to forcely kill my terminal.

What to do????

**Comment by hrqmonteiro** [comment]
It just completely freezes my terminal window, wtf is this?

![Screenshot from 2023-01-13 21-29-01](https://user-images.githubusercontent.com/17055027/212441241-0613b61b-48c2-4488-9523-bc74c7f74ac2.png)

**Comment by shaunsingh** [comment]
Did you read what the terminal was telling you during `nyoom sync`? If you want to install tree-sitter parsers ahead of time, hit `y` when it asks you `Do you want to install tree-sitter parses?`. If you don't, then nyoom attempts to install the nessecary parsers upon first startup

Tree-sitter parsers take a while to download and/or compile.
