### ISSUE TITLE
Quirk with `gcc` keymap on fresh installation

### ISSUE THREAD

**Issue by ejuarezg** [nyoom-engineering/nyoom.nvim#109]
Hi, 

New user of Nyoom. I came a across a quirk (or bug?) when trying to comment out a line with `gcc` keymap. Opening the `config.fnl` file and typing the `gcc` keymap does nothing. I have to run `<Space>c` first for `gcc` to work as intended. I suspect this has to do something with the lazy loading of Comment.nvim, but I am not too sure.
Here's some extra info:

```
Nyoom version: b558a53
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Comment by ejuarezg** [comment]
Any one else experienced this issue?

**Comment by shaunsingh** [comment]
I can reproduce the issue, I'll fix it in the next update

**Comment by ejuarezg** [comment]
Awesome! Thanks.
