### ISSUE TITLE
Error - Packer not found

### ISSUE THREAD

**Issue by dead8309** [nyoom-engineering/nyoom.nvim#111]
> Nyoom version: b558a53
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builder@24238d0703f7

> Clearing cacheUnable to require hotpotError detected while processing command line:
E5108: Error executing lua [string ":lua"]:1: module 'packer' not found:
        no field package.preload['packer']
        no file './packer.lua'
        no file '/data/data/com.termux/files/usr/share/luajit-2.1.0-beta3/packer.lua'
        no file '/usr/local/share/lua/5.1/packer.lua'
        no file '/usr/local/share/lua/5.1/packer/init.lua'
        no file '/data/data/com.termux/files/usr/share/lua/5.1/packer.lua'
        no file '/data/data/com.termux/files/usr/share/lua/5.1/packer/init.lua'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/data/data/com.termux/files/usr/lib/lua/5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk

Does this work on Termux(terminal emulator on Android) ?

**Comment by shaunsingh** [comment]
I think it should be fine. I'd delete `~/.local/share/nvim` and then re-run `nyoom install` just to make sure packer is all installed and set

**Comment by dead8309** [comment]
Thanks. That worked!
