### ISSUE TITLE
broken lspconfig

### ISSUE THREAD

**Issue by fushiii** [nyoom-engineering/nyoom.nvim#122]
Some language modules that depend on lspconfig are not working at the moment. That has happened with clangd, as well as rust,

When you try to use nyoom with either of the servers mentioned above, you will get the error:
`[lspconfig] Cannot access configuration for SERVER. Ensure this server is listed in server_configurations.md or added as a custom server.`

I am not really sure how i could help in this, as i really have no idea how to use lisp.

**Comment by dennisorlando** [comment]
Same problem for rust-analyzer; I performed a "sudo pacman -S neovim-lspconfig" command and the problem somehow magically disappeared, although I have no idea why.
Btw: the error that you got disappeared for me but I still got some other errors for rust-tools which I have to open an issue for
