### ISSUE TITLE
How to install in Windows?

### ISSUE THREAD

**Issue by KSaiAkshit** [nyoom-engineering/nyoom.nvim#125]
I am using Powershell 7.3.3 in the Windows Terminal. I know someone will inevitably bring up WSL, but I already have a separate config on WSL, and I'd like to try this out on `pwsh` before I make the switch. 
I've tried to execute the given commands:
`bin/nyoom install`,
but that just asks me which app to open `nyoom` with.

**Comment by shaunsingh** [comment]
I haven't tested nyoom with windows, and currently the script looks for XDG directories and unix-isms, so it probably doesn't work with windows. 

Currently, I use nyoom on windows through wsl2. Proper (non-wsl) windows is planned

**Comment by KSaiAkshit** [comment]
Great. I want to help in any way I can!
