### ISSUE TITLE
LUA-related errors when opening c++ and rust files

### ISSUE THREAD

**Issue by dennisorlando** [nyoom-engineering/nyoom.nvim#126]
Hi, I just installed freshly nyoom-neovim. I get this two errors when I try to open a rust file which I'm not sure where they come from and whether they are safe to ignore or not:
![image](https://user-images.githubusercontent.com/47061464/228078407-4a58c396-20aa-4030-8a82-8563fa66574e.png)
...then followed by this notification:
![image](https://user-images.githubusercontent.com/47061464/228078466-e4489658-bfb4-4f5e-8292-2e00bc525088.png)

**Comment by dennisorlando** [comment]
EDIT: this error appears to also happen for c++, but not with lua and python

**Comment by shaunsingh** [comment]
I believe this should be fixed for c++ and rust now
