### ISSUE TITLE
"Error detected while processing BufWritePre Autocommands for "<buffer=1>" when writing to file with :w

### ISSUE THREAD

**Issue by dennisorlando** [nyoom-engineering/nyoom.nvim#127]
![image](https://user-images.githubusercontent.com/47061464/228079098-0d97037b-3e62-46a9-a104-4983e216ce71.png)
This error does not happen with plain text files (without an extension) but does so for each "source" file (.lua, .rs, .cpp)

**Comment by steale-dot** [comment]
I can confirm this on the WIP web-module also appearing (e.g. js)

**Comment by thebashpotato** [comment]
Same issue here for rust, cpp, and python files

**Comment by therealnv6** [comment]
Same issue here, but buffer=23, specifically cpp. `Error detected while processing BufWritePre Autocommands for "<buffer=23>":`

**Comment by shaunsingh** [comment]
I believe this should be fixed now
