### ISSUE TITLE
Deprecated use of filetype 'help' in 'nvim/fnl/modules/config/tree-sitter/config.fnl'

### ISSUE THREAD

**Issue by philippeLL1** [nyoom-engineering/nyoom.nvim#128]
Hi everyone,

I've noticed that this [file](https://github.com/nyoom-engineering/nyoom.nvim/blob/main/fnl/modules/tools/tree-sitter/config.fnl) contains the following at line 11:
`(local treesitter-filetypes [:help :fennel :vim :regex :query])`

This generates a packer error message along the lines of `nvim-treesitter parser not available for language "help"`, because the `help` parser was renamed to `vimdoc` as per [this breaking change](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1492982270).

Changing line 11 to this fixes the issue:
`(local treesitter-filetypes [:vimdoc :fennel :vim :regex :query])`

I'm quite new to git/github, so please correct me if I've done anything wrong/forgotten anything! 
Just wanted to put this out there in case anyone else is experiencing the same issue.

Cheers!

**Comment by DanTheComrade** [comment]
Hi I experienced this too when I installed nyoom, although the fix isn't much it is atleast helpful so you don't have to go into the source code and change it so errors don't show up
I'm also kinda new to git/github so I'm kind of not sure whether I did something wrong lol. Hopefully the pr is merged as this can be annoying to new nyoom/(neo)vim users like me
