### ISSUE TITLE
Changing window title doesn't work

### ISSUE THREAD

**Issue by itaysharir** [nyoom-engineering/nyoom.nvim#141]
I tried to change the window title by adding 
```
vim.opt.title = true
vim.opt.titlelen = 0 -- do not shorten title
vim.opt.titlestring = 'nvim %{expand("%:p")}' 
```
To the end of my ```init.lua``` but it didn't work. It did work when i deleted the rest of the ```init.lua``` though. So what's preventing this from working?

**Comment by shaunsingh** [comment]
The equivalent fennel code is below: 

```lisp
(set! title)
(set! titlelen 0)
(set! titlestring "nvim %{expand(\"%:p\")}")
```

It works for me 
<img width="1440" alt="image" src="https://github.com/nyoom-engineering/nyoom.nvim/assets/71196912/058dd15c-4d6f-496e-95c2-27eeab853719">

Make sure to put it at the end of your `config.fnl`, let me know if you need anything
