### ISSUE TITLE
Wrong line color in insert mode

### ISSUE THREAD

**Issue by humblepenguinn** [nyoom-engineering/nyoom.nvim#145]
I changed my default colortheme to codedark (https://github.com/Mofiqul/vscode.nvim). However when I switch to insert mode the line color changes to a purple color which is not correct. 

I tried some other themes and it seems like the line color stays purple in insert mode. However if I open the editor without specifying any file, the line color in insert mode does not switch to purple. It is a bit weird so any sort of help would be appreciated!

Neovim version: v0.9.0

![Screenshot from 2023-07-02 16-27-50](https://github.com/nyoom-engineering/nyoom.nvim/assets/92458623/b932e5f2-1f77-4427-a795-92473084521f)

**Comment by shaunsingh** [comment]
```
        :ui
        (nyoom +modes +icons); what makes Nyoom look the way it does

```

remove the `+modes` flag so it looks like this 

```
        :ui
        (nyoom +icons); what makes Nyoom look the way it does
```
