### ISSUE TITLE
Question: What plugin and setup does nyoom use for autocomplete?

### ISSUE THREAD

**Issue by ostap-tymchenko** [nyoom-engineering/nyoom.nvim#146]
Hello, I quite like nyoom's autocomplete (see screenshot), i like how fast it is and how info dense it is.
![image](https://github.com/nyoom-engineering/nyoom.nvim/assets/56374185/61e2bf52-81bb-4cd6-982a-d7f2b60b26a6)
Mine is not that good. I used [this article](https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/) to make mine and mine looks more like this:
![image](https://github.com/nyoom-engineering/nyoom.nvim/assets/56374185/148f3945-84ea-42ad-b859-d229359f291d)
And although I do think its nice, I still prefer nyoom's. What plugin and lua configs does nyoom use for this?

also what is the configs and plugin for the bufferline?

**Comment by jn64** [comment]
See init.fnl and config.fnl in [fnl/modules/completion/cmp](https://github.com/nyoom-engineering/nyoom.nvim/tree/main/fnl/modules/completion/cmp)

**Comment by shaunsingh** [comment]
We use cmp along with a bit of config for the looks. You can use vscode's codicons for the icons
