### ISSUE TITLE
Telescope notify extension not installed

### ISSUE THREAD

**Issue by benjstephenson** [nyoom-engineering/nyoom.nvim#88]
On a fresh install, I get this error from telescope when I open nvim and do a `<leader>ff` to search for a file.

`...er/opt/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'notify' extension doesn't exist or isn't installed: module 'telescope._extensions.notify' not found:
	no field package.preload['telescope._extensions.notify`

If I do the same action again I don't get the error message so I'm guessing it's a lazy load ordering problem maybe? 
I'm new to nyoom and fennel so I'm not too sure on how to debug it.

**Comment by shaunsingh** [comment]
Thanks, it should be fixed in the latest commit
