### ISSUE TITLE
Discord link in README is invalid (again)

### ISSUE THREAD

**Issue by thezaff** [nyoom-engineering/nyoom.nvim#91]
Hi, the discord link in README is invalid. I saw there was a commit to fix it a week ago, but I wanted to join the server today and the link is invalid.

**Comment by shaunsingh** [comment]
Thanks, should be fixed now

**Comment by luxus** [comment]
you can change the validation time of a link (so it will not expire)

**Comment by shaunsingh** [comment]
Yup, I did it last time and then pasted the wrong link.
