### ISSUE TITLE
FR: auto-adjust the size of the logo, so that every items fit into the screen even on small screens

### ISSUE THREAD

**Issue by glyh** [nyoom-engineering/nyoom.nvim#94]
On my screen it looks like this:
![image](https://user-images.githubusercontent.com/12870742/209010269-c63657d9-d896-415e-81fc-84e520d192ae.png)

**Comment by N0TiNSiGHT** [comment]
You can configure the initial screen by yourself, just go to ```/fnl/modules/ui/dashboard/config.fnl``` and you will see the Doom screen. You can change it to other ASCII/Braille/Unicode art to your liking, though I'll agree that the Doom screen is too big for my tablet screen.

**Comment by shaunsingh** [comment]
I'll look into different asciii based on screen size, it fits fine on my 14 inch screen at a font hieght of 14, though I agree that it might not fit for others (including you). I'll look into it, thanks. 

> just go to /fnl/modules/ui/dashboard/config.fnl

It's recommended to use the `after` function inside `config.fnl` instead. E.g.
```fennel
(after :alpha {:layout [{:header {:type :text :val "your ascii goes here"}}]})
```

**Comment by shaunsingh** [comment]
In emacs my solution was just to scale the font size of the text itself, obviously this isn't possible in Neovim. At the same time, the current logo looks pretty bad if I rewrite it with smaller text. Maybe we should have two logos, one big and one small?
