### ISSUE TITLE
module 'packages' not found: Compiler error 

### ISSUE THREAD

**Issue by glyh** [nyoom-engineering/nyoom.nvim#98]
Here's the config I tried in packages.fnl:
```
(use-package! :shaunsingh/nord.nvim {:config (fn [] (. (require :nord) set))})

```

**Comment by N0TiNSiGHT** [comment]
> ```{:config (fn [] (. (require :nord) set))}```

Sorry, but I why are you calling for config function for the packer command?  If you want to set colorscheme then there's a macro 
``` (colorscheme your_colorscheme) ```
Put it in your fnl/config.fnl, but if you're trying to set theme for lualine, (taken from the theme's site)
```
require('lualine').setup {
  options = {
    -- ... your lualine config
    theme = 'nord'
    -- ... your lualine config
  }
}
```
use 
```
((. (require :lualine) :setup) {:options { :theme nord})
```

**Comment by shaunsingh** [comment]
Although its recommend to use `(colorscheme nord)` in `config.fnl`, this is also a totally fine way of configuring it 

In this case, it seems like you're not passing set as a string. The correct config should be 
```fennel
(use-package! :shaunsingh/nord.nvim {:config (fn [] (. (require :nord) :set))})
```

**Comment by shaunsingh** [comment]
@N0TiNSiGHT There were quite a few work in progress things I accidentally pushed that I didn't mean to, one of those changes was the dashboard 

All of the keymaps on the dashboard are temporary until I finish implementing that functionality (agenda, sessions, projects, documentation, marks)

**Comment by glyh** [comment]
Yeah it turns out using colorscheme macros work better with this distribution, o.w. it causes wierd colors. I'll close it.
